object Versions {

    // Android
    const val androidCompileSdk = 26
    const val androidMinSdk = 22
    const val androidTargetSdk = 22

    const val constraintLayout = "1.0.2"
    const val supportLibrary = "27.0.2"

    // App Libraries
    const val dagger = "2.14.1"
    const val glassfishAnnotation = "10.0-b28"
    const val glide = "4.4.0"
    const val gson = "2.8.1"
    const val javaxAnnotation = "1.0"
    const val javaxInject = "1"
    const val kotlin = "1.2.30"
    const val leakCanary = "1.5.4"
    const val okHttp = "3.8.1"
    const val retrofit = "2.3.0"
    const val room = "1.0.0"
    const val arch = "1.0.0"
    const val rxAndroid = "2.0.1"
    const val rxJava = "2.0.2"
    const val rxKotlin = "2.1.0"
    const val stetho = "1.5.0"
    const val timber = "4.5.1"
    const val anko = "0.10.4"
    const val firebase = "12.0.1"
    const val crashlytics = "2.9.1"
    const val simpleRecyclerView = "2.0.1"
    const val multidex = "1.0.0"
    const val playServices = "12.0.1"


    // Test Libraries
    const val androidSupportRules = "1.0.0"
    const val androidSupportRunner = "1.0.0"
    const val assertJ = "3.8.0"
    const val dexmakerMockito = "2.2.0"
    const val dexopener = "0.10.1"
    const val espresso = "3.0.0"
    const val jUnit = "4.12"
    const val mockitoKotlin = "1.5.0"
    const val robolectric = "3.4.2"
    const val runner = "0.5"
}

object AppDependencies {
    const val androidSupportAnnotations = "com.android.support:support-annotations:${Versions.supportLibrary}"
    const val androidSupportAppCompatV7 = "com.android.support:appcompat-v7:${Versions.supportLibrary}"
    const val androidSupportCardview = "com.android.support:cardview-v7:${Versions.supportLibrary}"
    const val androidSupportConstraintLayout = "com.android.support.constraint:constraint-layout:${Versions.constraintLayout}"
    const val androidSupportDesign = "com.android.support:design:${Versions.supportLibrary}"
    const val androidSupportRecyclerView = "com.android.support:recyclerview-v7:${Versions.supportLibrary}"
    const val androidSupportV13 = "com.android.support:support-v13:${Versions.supportLibrary}"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val daggerProcessor = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    const val daggerSupport = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    const val glassfishAnnotation = "org.glassfish:javax.annotation:${Versions.glassfishAnnotation}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glideHttp = "com.github.bumptech.glide:okhttp3-integration:${Versions.glide}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glide}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val javaxAnnotation = "javax.annotation:jsr250-api:${Versions.javaxAnnotation}"
    const val javaxInject = "javax.inject:javax.inject:${Versions.javaxInject}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jre8:${Versions.kotlin}"
    const val leakCanaryDebug = "com.squareup.leakcanary:leakcanary-android:${Versions.leakCanary}"
    const val leakCanaryRelease = "com.squareup.leakcanary:leakcanary-android-no-op:${Versions.leakCanary}"
    const val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    const val okHttpLogger = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    const val retrofitConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val archRuntime = "android.arch.lifecycle:runtime:${Versions.arch}"
    const val archExtensions = "android.arch.lifecycle:extensions:${Versions.arch}"
    const val archCompiler = "android.arch.lifecycle:compiler:${Versions.arch}"
    const val roomCompiler = "android.arch.persistence.room:compiler:${Versions.room}"
    const val roomRuntime = "android.arch.persistence.room:runtime:${Versions.room}"
    const val roomRxJava = "android.arch.persistence.room:rxjava2:${Versions.room}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    const val rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    const val rxKotlin = "io.reactivex.rxjava2:rxkotlin:${Versions.rxKotlin}"
    const val stetho = "com.facebook.stetho:stetho:${Versions.stetho}"
    const val stethoOkhttp3 = "com.facebook.stetho:stetho-okhttp3:${Versions.stetho}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val anko = "org.jetbrains.anko:anko-commons:${Versions.anko}"
    const val firebaseCore = "com.google.firebase:firebase-core:${Versions.firebase}"
    const val crashlytics = "com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}"
    const val firebasePerfMon = "com.google.firebase:firebase-perf:${Versions.firebase}"
    const val simpleRecyclerView = "com.jaychang:simplerecyclerview:${Versions.simpleRecyclerView}"
    const val simpleRecyclerViewKotlinEx = "com.jaychang:simplerecyclerview-kotlin-android-extensions:${Versions.simpleRecyclerView}"
    const val multidex = "com.android.support:multidex:${Versions.multidex}"
    const val playServices = "com.google.android.gms:play-services:${Versions.playServices}"

}

object TestDependencies {
    const val androidRules = "com.android.support.test:rules:${Versions.runner}"
    const val androidRunner = "com.android.support.test:runner:${Versions.runner}"
    const val assertj = "org.assertj:assertj-core:${Versions.assertJ}"
    const val dexmakerMockito = "com.linkedin.dexmaker:dexmaker-mockito:${Versions.dexmakerMockito}"
    const val dexopener = "com.github.tmurakami:dexopener:${Versions.dexopener}"
    const val espressoContrib = "com.android.support.test.espresso:espresso-contrib:${Versions.espresso}"
    const val espressoCore = "com.android.support.test.espresso:espresso-core:${Versions.espresso}"
    const val espressoIntents = "com.android.support.test.espresso:espresso-intents:${Versions.espresso}"
    const val junit = "junit:junit:${Versions.jUnit}"
    const val kotlinJUnit = "org.jetbrains.kotlin:kotlin-test-junit:${Versions.kotlin}"
    const val mockitoKotlin = "com.nhaarman:mockito-kotlin:${Versions.mockitoKotlin}"
    const val robolectric = "org.robolectric:robolectric:${Versions.robolectric}"
    const val roomTesting = "android.arch.persistence.room:testing:${Versions.room}"
    const val supportRules = "com.android.support.test:rules:${Versions.androidSupportRules}"
    const val supportRunner = "com.android.support.test:runner:${Versions.androidSupportRunner}"
}